//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Filtering
{

    public sealed class BinaryFilterExpressionItem 
    {

        

        dynamic binaryfilterexpressionitem;
        
        public BinaryFilterExpressionItem()
        {
            this.binaryfilterexpressionitem =  TSActivator.CreateInstance("Tekla.Structures.Filtering.BinaryFilterExpressionItem");
        }

        public BinaryFilterExpressionItem(dynamic tsObject)
        {
            this.binaryfilterexpressionitem = tsObject;
        }

        internal dynamic GetTSObject() => binaryfilterexpressionitem;





    }

}
    
