//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Filtering
{

    public sealed class DateTimeConstantFilterExpression 
    {

        

        internal dynamic datetimeconstantfilterexpression;
        
        public DateTimeConstantFilterExpression()
        {
            this.datetimeconstantfilterexpression =  TSActivator.CreateInstance("Tekla.Structures.Filtering.DateTimeConstantFilterExpression");
        }

        internal DateTimeConstantFilterExpression(dynamic tsObject)
        {
            this.datetimeconstantfilterexpression = tsObject;
        }
		public DateTimeConstantFilterExpression(System.DateTime Value)
		{
			var args = new object[1];
			args[0] = Value;
			this.datetimeconstantfilterexpression = TSActivator.CreateInstance("Tekla.Structures.Filtering.DateTimeConstantFilterExpression", args);
		}
		public DateTimeConstantFilterExpression(System.Collections.Generic.IEnumerable<System.DateTime> Values)
		{
			var args = new object[1];
			args[0] = Values;
			this.datetimeconstantfilterexpression = TSActivator.CreateInstance("Tekla.Structures.Filtering.DateTimeConstantFilterExpression", args);
		}
		public DateTimeConstantFilterExpression(System.DateTime Value, System.IFormatProvider Provider)
		{
			var args = new object[2];
			args[0] = Value;
			args[1] = Provider;
			this.datetimeconstantfilterexpression = TSActivator.CreateInstance("Tekla.Structures.Filtering.DateTimeConstantFilterExpression", args);
		}
		public DateTimeConstantFilterExpression(System.Collections.Generic.IEnumerable<System.DateTime> Values, System.IFormatProvider Provider)
		{
			var args = new object[2];
			args[0] = Values;
			args[1] = Provider;
			this.datetimeconstantfilterexpression = TSActivator.CreateInstance("Tekla.Structures.Filtering.DateTimeConstantFilterExpression", args);
		}





    }

    internal static class DateTimeConstantFilterExpression_
    {
        public static dynamic GetTSObject(DateTimeConstantFilterExpression dynObject)
        {
            return dynObject.datetimeconstantfilterexpression;
        }

        public static DateTimeConstantFilterExpression FromTSObject(dynamic tsObject)
        {
            return new DateTimeConstantFilterExpression(tsObject);
        }
    }


}
    
