//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Filtering
{

    public  class DateTimeFilterExpression  : Dynamic.Tekla.Structures.Filtering.DataFilterExpression
    {

        

        internal dynamic teklaObject;

		internal DateTimeFilterExpression() {}





    }

    internal static class DateTimeFilterExpression_
    {
        public static dynamic GetTSObject(DateTimeFilterExpression dynObject)
        {
            return dynObject.teklaObject;
        }

        public static DateTimeFilterExpression FromTSObject(dynamic tsObject)
        {
            return new DateTimeFilterExpression() { teklaObject = tsObject };
        }
    }


}
    
