//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Filtering.Categories
{

    public sealed class PourUnitFilterExpressions 
    {

        

        internal dynamic pourunitfilterexpressions;
        
        public PourUnitFilterExpressions()
        {
            this.pourunitfilterexpressions =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions");
        }

        internal PourUnitFilterExpressions(dynamic tsObject)
        {
            this.pourunitfilterexpressions = tsObject;
        }




    public sealed class CustomBoolean 
    {

        

        internal dynamic customboolean;
        
        public CustomBoolean()
        {
            this.customboolean =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions.CustomBoolean");
        }

        internal CustomBoolean(dynamic tsObject)
        {
            this.customboolean = tsObject;
        }
		public CustomBoolean(System.String UserAttribute)
		{
			var args = new object[1];
			args[0] = UserAttribute;
			this.customboolean = TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions.CustomBoolean", args);
		}





    }

    internal static class CustomBoolean_
    {
        public static dynamic GetTSObject(CustomBoolean dynObject)
        {
            return dynObject.customboolean;
        }

        public static CustomBoolean FromTSObject(dynamic tsObject)
        {
            return new CustomBoolean(tsObject);
        }
    }



    public sealed class CustomDateTime 
    {

        

        internal dynamic customdatetime;
        
        public CustomDateTime()
        {
            this.customdatetime =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions.CustomDateTime");
        }

        internal CustomDateTime(dynamic tsObject)
        {
            this.customdatetime = tsObject;
        }
		public CustomDateTime(System.String UserAttribute)
		{
			var args = new object[1];
			args[0] = UserAttribute;
			this.customdatetime = TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions.CustomDateTime", args);
		}





    }

    internal static class CustomDateTime_
    {
        public static dynamic GetTSObject(CustomDateTime dynObject)
        {
            return dynObject.customdatetime;
        }

        public static CustomDateTime FromTSObject(dynamic tsObject)
        {
            return new CustomDateTime(tsObject);
        }
    }



    public sealed class CustomNumber 
    {

        

        internal dynamic customnumber;
        
        public CustomNumber()
        {
            this.customnumber =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions.CustomNumber");
        }

        internal CustomNumber(dynamic tsObject)
        {
            this.customnumber = tsObject;
        }
		public CustomNumber(System.String UserAttribute)
		{
			var args = new object[1];
			args[0] = UserAttribute;
			this.customnumber = TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions.CustomNumber", args);
		}





    }

    internal static class CustomNumber_
    {
        public static dynamic GetTSObject(CustomNumber dynObject)
        {
            return dynObject.customnumber;
        }

        public static CustomNumber FromTSObject(dynamic tsObject)
        {
            return new CustomNumber(tsObject);
        }
    }



    public sealed class CustomString 
    {

        

        internal dynamic customstring;
        
        public CustomString()
        {
            this.customstring =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions.CustomString");
        }

        internal CustomString(dynamic tsObject)
        {
            this.customstring = tsObject;
        }
		public CustomString(System.String UserAttribute)
		{
			var args = new object[1];
			args[0] = UserAttribute;
			this.customstring = TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions.CustomString", args);
		}





    }

    internal static class CustomString_
    {
        public static dynamic GetTSObject(CustomString dynObject)
        {
            return dynObject.customstring;
        }

        public static CustomString FromTSObject(dynamic tsObject)
        {
            return new CustomString(tsObject);
        }
    }



    public sealed class Name 
    {

        

        internal dynamic name;
        
        public Name()
        {
            this.name =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions.Name");
        }

        internal Name(dynamic tsObject)
        {
            this.name = tsObject;
        }





    }

    internal static class Name_
    {
        public static dynamic GetTSObject(Name dynObject)
        {
            return dynObject.name;
        }

        public static Name FromTSObject(dynamic tsObject)
        {
            return new Name(tsObject);
        }
    }



    public sealed class Guid 
    {

        

        internal dynamic guid;
        
        public Guid()
        {
            this.guid =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions.Guid");
        }

        internal Guid(dynamic tsObject)
        {
            this.guid = tsObject;
        }





    }

    internal static class Guid_
    {
        public static dynamic GetTSObject(Guid dynObject)
        {
            return dynObject.guid;
        }

        public static Guid FromTSObject(dynamic tsObject)
        {
            return new Guid(tsObject);
        }
    }




    }

    internal static class PourUnitFilterExpressions_
    {
        public static dynamic GetTSObject(PourUnitFilterExpressions dynObject)
        {
            return dynObject.pourunitfilterexpressions;
        }

        public static PourUnitFilterExpressions FromTSObject(dynamic tsObject)
        {
            return new PourUnitFilterExpressions(tsObject);
        }
    }


}
    
