//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Filtering.Categories
{

    public sealed class PourBreakFilterExpressions 
    {

        

        internal dynamic pourbreakfilterexpressions;
        
        public PourBreakFilterExpressions()
        {
            this.pourbreakfilterexpressions =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourBreakFilterExpressions");
        }

        internal PourBreakFilterExpressions(dynamic tsObject)
        {
            this.pourbreakfilterexpressions = tsObject;
        }




    public sealed class CustomBoolean 
    {

        

        internal dynamic customboolean;
        
        public CustomBoolean()
        {
            this.customboolean =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourBreakFilterExpressions.CustomBoolean");
        }

        internal CustomBoolean(dynamic tsObject)
        {
            this.customboolean = tsObject;
        }
		public CustomBoolean(System.String UserAttribute)
		{
			var args = new object[1];
			args[0] = UserAttribute;
			this.customboolean = TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourBreakFilterExpressions.CustomBoolean", args);
		}





    }

    internal static class CustomBoolean_
    {
        public static dynamic GetTSObject(CustomBoolean dynObject)
        {
            return dynObject.customboolean;
        }

        public static CustomBoolean FromTSObject(dynamic tsObject)
        {
            return new CustomBoolean(tsObject);
        }
    }



    public sealed class CustomDateTime 
    {

        

        internal dynamic customdatetime;
        
        public CustomDateTime()
        {
            this.customdatetime =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourBreakFilterExpressions.CustomDateTime");
        }

        internal CustomDateTime(dynamic tsObject)
        {
            this.customdatetime = tsObject;
        }
		public CustomDateTime(System.String UserAttribute)
		{
			var args = new object[1];
			args[0] = UserAttribute;
			this.customdatetime = TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourBreakFilterExpressions.CustomDateTime", args);
		}





    }

    internal static class CustomDateTime_
    {
        public static dynamic GetTSObject(CustomDateTime dynObject)
        {
            return dynObject.customdatetime;
        }

        public static CustomDateTime FromTSObject(dynamic tsObject)
        {
            return new CustomDateTime(tsObject);
        }
    }



    public sealed class CustomNumber 
    {

        

        internal dynamic customnumber;
        
        public CustomNumber()
        {
            this.customnumber =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourBreakFilterExpressions.CustomNumber");
        }

        internal CustomNumber(dynamic tsObject)
        {
            this.customnumber = tsObject;
        }
		public CustomNumber(System.String UserAttribute)
		{
			var args = new object[1];
			args[0] = UserAttribute;
			this.customnumber = TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourBreakFilterExpressions.CustomNumber", args);
		}





    }

    internal static class CustomNumber_
    {
        public static dynamic GetTSObject(CustomNumber dynObject)
        {
            return dynObject.customnumber;
        }

        public static CustomNumber FromTSObject(dynamic tsObject)
        {
            return new CustomNumber(tsObject);
        }
    }



    public sealed class CustomString 
    {

        

        internal dynamic customstring;
        
        public CustomString()
        {
            this.customstring =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourBreakFilterExpressions.CustomString");
        }

        internal CustomString(dynamic tsObject)
        {
            this.customstring = tsObject;
        }
		public CustomString(System.String UserAttribute)
		{
			var args = new object[1];
			args[0] = UserAttribute;
			this.customstring = TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourBreakFilterExpressions.CustomString", args);
		}





    }

    internal static class CustomString_
    {
        public static dynamic GetTSObject(CustomString dynObject)
        {
            return dynObject.customstring;
        }

        public static CustomString FromTSObject(dynamic tsObject)
        {
            return new CustomString(tsObject);
        }
    }




    }

    internal static class PourBreakFilterExpressions_
    {
        public static dynamic GetTSObject(PourBreakFilterExpressions dynObject)
        {
            return dynObject.pourbreakfilterexpressions;
        }

        public static PourBreakFilterExpressions FromTSObject(dynamic tsObject)
        {
            return new PourBreakFilterExpressions(tsObject);
        }
    }


}
    
