//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Filtering.Categories
{

    public sealed class PourUnitFilterExpressions 
    {

        

        dynamic pourunitfilterexpressions;
        
        public PourUnitFilterExpressions()
        {
            this.pourunitfilterexpressions =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.PourUnitFilterExpressions");
        }

        public PourUnitFilterExpressions(dynamic tsObject)
        {
            this.pourunitfilterexpressions = tsObject;
        }

        internal dynamic GetTSObject() => pourunitfilterexpressions;




    public sealed class CustomBoolean 
    {

        

        dynamic customboolean;
        
        public CustomBoolean()
        {
            this.customboolean =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.CustomBoolean");
        }

        public CustomBoolean(dynamic tsObject)
        {
            this.customboolean = tsObject;
        }

        internal dynamic GetTSObject() => customboolean;





    }


    public sealed class CustomDateTime 
    {

        

        dynamic customdatetime;
        
        public CustomDateTime()
        {
            this.customdatetime =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.CustomDateTime");
        }

        public CustomDateTime(dynamic tsObject)
        {
            this.customdatetime = tsObject;
        }

        internal dynamic GetTSObject() => customdatetime;





    }


    public sealed class CustomNumber 
    {

        

        dynamic customnumber;
        
        public CustomNumber()
        {
            this.customnumber =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.CustomNumber");
        }

        public CustomNumber(dynamic tsObject)
        {
            this.customnumber = tsObject;
        }

        internal dynamic GetTSObject() => customnumber;





    }


    public sealed class CustomString 
    {

        

        dynamic customstring;
        
        public CustomString()
        {
            this.customstring =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.CustomString");
        }

        public CustomString(dynamic tsObject)
        {
            this.customstring = tsObject;
        }

        internal dynamic GetTSObject() => customstring;





    }


    public sealed class Name 
    {

        

        dynamic name;
        
        public Name()
        {
            this.name =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.Name");
        }

        public Name(dynamic tsObject)
        {
            this.name = tsObject;
        }

        internal dynamic GetTSObject() => name;





    }


    public sealed class Guid 
    {

        

        dynamic guid;
        
        public Guid()
        {
            this.guid =  TSActivator.CreateInstance("Tekla.Structures.Filtering.Categories.Guid");
        }

        public Guid(dynamic tsObject)
        {
            this.guid = tsObject;
        }

        internal dynamic GetTSObject() => guid;





    }



    }

}
    
