//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures
{

    public struct TeklaStructuresDatabaseTypeEnum
    {
       
    }

    internal static class TeklaStructuresDatabaseTypeEnum_
    {
        public static dynamic GetTSObject(TeklaStructuresDatabaseTypeEnum dynStruct)
        {
            var tsType = TSActivator.CreateInstance("Tekla.Structures.TeklaStructuresDatabaseTypeEnum");

            return tsType;
        }
    
        public static TeklaStructuresDatabaseTypeEnum FromTSObject(dynamic tsStruct)
        {
            var dynStruct = new TeklaStructuresDatabaseTypeEnum();
 
            return dynStruct;
        }
    }

}
    
