//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public  class ClashCheckHandler 
    {

        

        internal dynamic teklaObject;

		public ClashCheckHandler() {}

		public System.Boolean RunClashCheck()
			 => teklaObject.RunClashCheck();

		public System.Boolean StopClashCheck()
			 => teklaObject.StopClashCheck();

		public System.Collections.ArrayList GetIntersectionBoundingBoxes(Dynamic.Tekla.Structures.Identifier ID1, Dynamic.Tekla.Structures.Identifier ID2)
			 => teklaObject.GetIntersectionBoundingBoxes(Dynamic.Tekla.Structures.Identifier_.GetTSObject(ID1), Dynamic.Tekla.Structures.Identifier_.GetTSObject(ID2));





    }

    internal static class ClashCheckHandler_
    {
        public static dynamic GetTSObject(ClashCheckHandler dynObject)
        {
            return dynObject.teklaObject;
        }

        public static ClashCheckHandler FromTSObject(dynamic tsObject)
        {
            var typeName = "Dynamic." + tsObject.GetType().FullName;
            var type = System.Reflection.Assembly.GetExecutingAssembly().GetType(typeName);
            var dynObject = (Tekla.Structures.Model.ClashCheckHandler)System.Activator.CreateInstance(type);
            dynObject.teklaObject = tsObject;
            return dynObject;
        }
    }


}
    
