//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public sealed class FacePerpendicularToIntersectionLineException 
    {

		public System.String Message
		{
			get => faceperpendiculartointersectionlineexception.Message;
			set { faceperpendiculartointersectionlineexception.Message = value; }
		}

		public System.Collections.IDictionary Data
		{
			get => faceperpendiculartointersectionlineexception.Data;
			set { faceperpendiculartointersectionlineexception.Data = value; }
		}

		public System.Exception InnerException
		{
			get => faceperpendiculartointersectionlineexception.InnerException;
			set { faceperpendiculartointersectionlineexception.InnerException = value; }
		}

		public System.Reflection.MethodBase TargetSite
		{
			get => faceperpendiculartointersectionlineexception.TargetSite;
			set { faceperpendiculartointersectionlineexception.TargetSite = value; }
		}

		public System.String StackTrace
		{
			get => faceperpendiculartointersectionlineexception.StackTrace;
			set { faceperpendiculartointersectionlineexception.StackTrace = value; }
		}

		public System.String HelpLink
		{
			get => faceperpendiculartointersectionlineexception.HelpLink;
			set { faceperpendiculartointersectionlineexception.HelpLink = value; }
		}

		public System.String Source
		{
			get => faceperpendiculartointersectionlineexception.Source;
			set { faceperpendiculartointersectionlineexception.Source = value; }
		}

		public System.Int32 HResult
		{
			get => faceperpendiculartointersectionlineexception.HResult;
			set { faceperpendiculartointersectionlineexception.HResult = value; }
		}

		public Dynamic.Tekla.Structures.Model.BentPlateGeometrySolver.OperationStatus OperationStatus
		{
			get => Dynamic.Tekla.Structures.Model.BentPlateGeometrySolver.OperationStatus_.FromTSObject(faceperpendiculartointersectionlineexception.OperationStatus);
			set { faceperpendiculartointersectionlineexception.OperationStatus = Dynamic.Tekla.Structures.Model.BentPlateGeometrySolver.OperationStatus_.GetTSObject(value); }
		}

        

        internal dynamic faceperpendiculartointersectionlineexception;
        
        public FacePerpendicularToIntersectionLineException()
        {
            this.faceperpendiculartointersectionlineexception =  TSActivator.CreateInstance("Tekla.Structures.Model.FacePerpendicularToIntersectionLineException");
        }

        internal FacePerpendicularToIntersectionLineException(dynamic tsObject)
        {
            this.faceperpendiculartointersectionlineexception = tsObject;
        }

		public System.Exception GetBaseException()
			 => faceperpendiculartointersectionlineexception.GetBaseException();

		public void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
			 => faceperpendiculartointersectionlineexception.GetObjectData(info, context);





    }

    internal static class FacePerpendicularToIntersectionLineException_
    {
        public static dynamic GetTSObject(FacePerpendicularToIntersectionLineException dynObject)
        {
            return dynObject.faceperpendiculartointersectionlineexception;
        }

        public static FacePerpendicularToIntersectionLineException FromTSObject(dynamic tsObject)
        {
            return new FacePerpendicularToIntersectionLineException(tsObject);
        }
    }


}
    
