//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public sealed class GeometrySection 
    {

		public System.Int32 Index
		{
			get => geometrysection.Index;
			set { geometrysection.Index = value; }
		}

		public Dynamic.Tekla.Structures.Model.IGeometryNode GeometryNode
		{
			get => new Dynamic.Tekla.Structures.Model.IGeometryNode(geometrysection.GeometryNode);
			set { geometrysection.GeometryNode = value.GetTSObject(); }
		}

        

        dynamic geometrysection;
        
        public GeometrySection()
        {
            this.geometrysection =  TSActivator.CreateInstance("Tekla.Structures.Model.GeometrySection");
        }

        public GeometrySection(dynamic tsObject)
        {
            this.geometrysection = tsObject;
			this.Index = geometrysection.Index;
			this.GeometryNode = new Dynamic.Tekla.Structures.Model.IGeometryNode(geometrysection.GeometryNode);

        }


        public dynamic GetTSObject() => geometrysection;





    }

}
    
