//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public sealed class NumberingSeriesNullable 
    {

		public System.String Prefix
		{
			get => numberingseriesnullable.Prefix;
			set { numberingseriesnullable.Prefix = value; }
		}

		public System.Int32 StartNumber
		{
			get => numberingseriesnullable.StartNumber;
			set { numberingseriesnullable.StartNumber = value; }
		}

        

        internal dynamic numberingseriesnullable;
        
        public NumberingSeriesNullable()
        {
            this.numberingseriesnullable =  TSActivator.CreateInstance("Tekla.Structures.Model.NumberingSeriesNullable");
        }

        internal NumberingSeriesNullable(dynamic tsObject)
        {
            this.numberingseriesnullable = tsObject;
        }
		public NumberingSeriesNullable(System.String prefix, System.Int32 number)
		{
			var args = new object[2];
			args[0] = prefix;
			args[1] = number;
			this.numberingseriesnullable = TSActivator.CreateInstance("Tekla.Structures.Model.NumberingSeriesNullable", args);
		}





    }

    internal static class NumberingSeriesNullable_
    {
        public static dynamic GetTSObject(NumberingSeriesNullable dynObject)
        {
            return dynObject.numberingseriesnullable;
        }

        public static NumberingSeriesNullable FromTSObject(dynamic tsObject)
        {
            return new NumberingSeriesNullable(tsObject);
        }
    }


}
    
