//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public  class Object 
    {

		public Dynamic.Tekla.Structures.Identifier Identifier
		{
			get => Dynamic.Tekla.Structures.Identifier_.FromTSObject(teklaObject.Identifier);
			set { teklaObject.Identifier = Dynamic.Tekla.Structures.Identifier_.GetTSObject(value); }
		}

        

        internal dynamic teklaObject;

		internal Object() {}





    }

    internal static class Object_
    {
        public static dynamic GetTSObject(Object dynObject)
        {
            return dynObject.teklaObject;
        }

        public static Object FromTSObject(dynamic tsObject)
        {
            return new Object() { teklaObject = tsObject };
        }
    }


}
    
