//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public sealed class Object 
    {

		public Dynamic.Tekla.Structures.Identifier Identifier
		{
			get => new Dynamic.Tekla.Structures.Identifier(@object.Identifier);
			set { @object.Identifier = value.GetTSObject(); }
		}

        

        dynamic @object;
        
        public Object()
        {
            this.@object =  TSActivator.CreateInstance("Tekla.Structures.Model.Object");
        }

        public Object(dynamic tsObject)
        {
            this.@object = tsObject;
			this.Identifier = new Dynamic.Tekla.Structures.Identifier(@object.Identifier);

        }


        public dynamic GetTSObject() => @object;





    }

}
    
