//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public  class UndefinedCurveDirectionException  : Dynamic.Tekla.Structures.Model.ConnectiveGeometryException
    {

        

        

		public UndefinedCurveDirectionException()
		{
			this.teklaObject = TSActivator.CreateInstance("Tekla.Structures.Model.UndefinedCurveDirectionException");
		}

		public System.Exception GetBaseException()
			 => teklaObject.GetBaseException();

		public void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
			 => teklaObject.GetObjectData(info, context);





    }

    internal static class UndefinedCurveDirectionException_
    {
        public static dynamic GetTSObject(UndefinedCurveDirectionException dynObject)
        {
            return dynObject.teklaObject;
        }

        public static UndefinedCurveDirectionException FromTSObject(dynamic tsObject)
        {
            var typeName = "Dynamic." + tsObject.GetType().FullName;
            var type = System.Reflection.Assembly.GetExecutingAssembly().GetType(typeName);
            var dynObject = (Tekla.Structures.Model.UndefinedCurveDirectionException)System.Activator.CreateInstance(type);
            dynObject.teklaObject = tsObject;
            return dynObject;
        }
    }


}
    
