//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Geometry3d
{

    public  class GeometryConstants 
    {

        

        internal dynamic teklaObject;

		public GeometryConstants()
		{
			this.teklaObject = TSActivator.CreateInstance("Tekla.Structures.Geometry3d.GeometryConstants");
		}





    }

    internal static class GeometryConstants_
    {
        public static dynamic GetTSObject(GeometryConstants dynObject)
        {
            return dynObject.teklaObject;
        }

        public static GeometryConstants FromTSObject(dynamic tsObject)
        {
            return new GeometryConstants() { teklaObject = tsObject };
        }
    }


}
    
