//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Geometry3d
{

    public sealed class ICurve 
    {

		public Dynamic.Tekla.Structures.Geometry3d.Point StartPoint
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Point_.FromTSObject(icurve.StartPoint);
			set { icurve.StartPoint = Dynamic.Tekla.Structures.Geometry3d.Point_.GetTSObject(value); }
		}

		public Dynamic.Tekla.Structures.Geometry3d.Point EndPoint
		{
			get => Dynamic.Tekla.Structures.Geometry3d.Point_.FromTSObject(icurve.EndPoint);
			set { icurve.EndPoint = Dynamic.Tekla.Structures.Geometry3d.Point_.GetTSObject(value); }
		}

		public System.Double Length
		{
			get => icurve.Length;
			set { icurve.Length = value; }
		}

        

        internal dynamic icurve;
        
        private ICurve()
        {
            this.icurve =  TSActivator.CreateInstance("Tekla.Structures.Geometry3d.ICurve");
        }

        internal ICurve(dynamic tsObject)
        {
            this.icurve = tsObject;
        }





    }

    internal static class ICurve_
    {
        public static dynamic GetTSObject(ICurve dynObject)
        {
            return dynObject.icurve;
        }

        public static ICurve FromTSObject(dynamic tsObject)
        {
            return new ICurve(tsObject);
        }
    }


}
    
