//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Model
{

    public sealed class ConicalSurfaceNode 
    {

		public Dynamic.Tekla.Structures.Model.ConicalSurface Surface
		{
			get => new Dynamic.Tekla.Structures.Model.ConicalSurface(conicalsurfacenode.Surface.GetTSObject());
			set { conicalsurfacenode.Surface = value.GetTSObject(); }
		}

		public System.Boolean IsAutomatic
		{
			get => conicalsurfacenode.IsAutomatic;
			set { conicalsurfacenode.IsAutomatic = value; }
		}

		public Dynamic.Tekla.Structures.Model.BendSurface Surface
		{
			get => new Dynamic.Tekla.Structures.Model.BendSurface(conicalsurfacenode.Surface.GetTSObject());
			set { conicalsurfacenode.Surface = value.GetTSObject(); }
		}

        

        dynamic conicalsurfacenode;
        
        public ConicalSurfaceNode()
        {
            this.conicalsurfacenode =  new Tekla.Structures.Model.ConicalSurfaceNode();
        }

        public ConicalSurfaceNode(dynamic tsObject)
        {
            this.conicalsurfacenode = tsObject;
			this.Surface = new Dynamic.Tekla.Structures.Model.ConicalSurface(conicalsurfacenode.Surface);
			this.IsAutomatic = conicalsurfacenode.IsAutomatic;
			this.Surface = new Dynamic.Tekla.Structures.Model.BendSurface(conicalsurfacenode.Surface);

        }


        public dynamic GetTSObject() => conicalsurfacenode;

		public void AcceptVisitor(Dynamic.Tekla.Structures.Model.IGeometryNodeVisitor visitor)
			 => conicalsurfacenode.AcceptVisitor(visitor.GetTSObject());

		public Dynamic.Tekla.Structures.Model.IGeometryNode Clone()
			 => new Dynamic.Tekla.Structures.Model.IGeometryNode(conicalsurfacenode.Clone());

		public System.Boolean Equals(System.Object obj)
			 => conicalsurfacenode.Equals(obj);

		public System.Int32 GetHashCode()
			 => conicalsurfacenode.GetHashCode();

		public System.Type GetType()
			 => conicalsurfacenode.GetType();

		public System.String ToString()
			 => conicalsurfacenode.ToString();





    }

}
    
