//Generated by script in project CodeGenerator
//Copyright Dawid Dyrcz 2020 see license file

namespace Dynamic.Tekla.Structures.Filtering
{

    public sealed class StringConstantFilterExpression 
    {

        

        dynamic stringconstantfilterexpression;
        
        public StringConstantFilterExpression()
        {
            this.stringconstantfilterexpression =  new Tekla.Structures.Filtering.StringConstantFilterExpression();
        }

        public StringConstantFilterExpression(dynamic tsObject)
        {
            this.stringconstantfilterexpression = tsObject;

        }


        public dynamic GetTSObject() => stringconstantfilterexpression;





    }

}
    
